import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 12

[font.bold]
family = "Roboto Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Roboto Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Roboto Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Roboto Mono Nerd Font"
style = "Regular"

[window]
dimensions = { columns = 128, lines = 32 }
padding = { x = 10, y = 1 }
