[general]
import = [
	"~/.config/alacritty/themes/gruvbox_dark_soft.toml"
]

[window]
opacity = 0.95
blur = true
padding = { x = 7, y = 7}
decorations = "None"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "regular" }
size = 9.5

[mouse]
hide_when_typing = true
