format = """
$os\
[](fg:#665c54 bg:#504945)\
$directory\
[](fg:#504945 bg:#3c3836)\
$git_branch\
$git_status\
[](fg:#3c3836 bg:#282828)\
$git_metrics\
[](fg:#282828 bg:#1d2021)\
$nodejs\
$rust\
$golang\
$lua\
$nim\
$php\
[](fg:#1d2021)"""

right_format = """
[](fg:#3c3836)\
$time
"""

# Disable the blank line at the start of the prompt
add_newline = false

[os]
style = 'fg:#ebdbb2 bg:#665c54'
format = '[ $symbol]($style)'
disabled = false

[directory]
style = 'fg:#83a598 bg:#504945'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'

[git_branch]
symbol = ''
style = 'fg:#b8bb26 bg:#3c3836'
format = '[ $symbol $branch ]($style)'

[git_status]
style = 'fg:#b8bb26 bg:#3c3836'
format = '[$state($all_status$ahead_behind )]($style)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_metrics]
added_style = 'fg:#8ec07c bg:#282828'
deleted_style = 'fg:#fe8019 bg:#282828'
format = '([ +$added ]($added_style))([-$deleted ]($deleted_style))'
disabled = false

[nodejs]
symbol = ''
style = 'fg:#d3869b bg:#1d2021'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ''
style = 'fg:#d3869b bg:#1d2021'
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = 'ﳑ'
style = 'fg:#d3869b bg:#1d2021'
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ''
style = 'fg:#d3869b bg:#1d2021'
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ' '
style = 'fg:#d3869b bg:#1d2021'
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = ' '
style = 'fg:#d3869b bg:#1d2021'
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = '%R'
style = 'fg:#83a598 bg:#3c3836'
format = '[  $time ]($style)'

[os.symbols]
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = ' '
Gentoo = ' '
HardenedBSD = 'ﲊ '
Illumos = ' '
Linux = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = ' '
openSUSE = ' '
OracleLinux = ' '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
Redox = ' '
Solus = 'ﴱ '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Windows = ' '
